#Archivo Seleccionado
#Fri Nov 28 23:48:49 CET 2025
archivoSeleccionado=C\:\\Users\\marcr\\Desktop\\Escritorio\\APLICACION\\Servidor\\Servidor de Archivos\\2\\1.Biologia\\1.Biologia\\1.Resumen.docx
idusuario=2
