#Archivo Seleccionado
#Wed Oct 22 18:42:55 CEST 2025
archivoSeleccionado=C\:\\Users\\marcr\\Desktop\\Escritorio\\APLICACION\\Servidor\\Servidor de Archivos\\1\\1.Matematicas\\1.numeros estructurados\\1.docsjs.odt
idusuario=1
