#Archivo Seleccionado
#Wed Dec 10 22:31:15 CET 2025
archivoSeleccionado=C\:\\Users\\marcr\\Desktop\\Escritorio\\APLICACION\\Servidor\\Servidor de Archivos\\2\\1.Biologia\\1.Biologia\\1.Resumen.docx
idusuario=2
